[spotify]
client_id = ""
client_secret = ""
auth_token_storage_dir = '~/.config/jukebox/'
username = ""
device_name = "Jukebox"

[panel]
input_device_name = "panel_keys"
timeout_minutes = 1
simulate = true

[leds]
host = "::1"
port = 5555
simulate = true

[animations]
A = "techno"
B = "techno"
C = "slow"
D = "slow"
E = "country"
F = "country"
G = "slow"
H = "fast"
J = "slow"
K = "slow"
L = "fast"
M = "fast"
N = "slow"
O = "slow"

P = ["solid", "#000000"]
P1 = ["solid", "#000080"]
P2 = ["solid", "#ff0000"]
P3 = ["solid", "#ffff00"]
P4 = ["solid", "#ff00ff"]
P5 = ["solid", "#ffff00"]
Q = ["solid", "#000080"]

[playback]
# A/B: Techno & House
A1 = "spotify:playlist:37i9dQZF1DX6GJXiuZRisr" # Night Rider
A2 = "spotify:playlist:5S33MuzhWWNW57z49eBSui" # Progressive House
A3 = "spotify:playlist:3oRNodhtGLVnZl0Q32FJHB" # Deep House 2020 Hits
A4 = "spotify:playlist:37i9dQZF1DX5xiztvBdlUf" # Truely Deeply House
A5 = "spotify:album:4Ijivtrfqk2AMTF4dhrl2Q" # The Algorithm - Brute Force
A6 = "spotify:playlist:1dYAJbmobktEp59pUPeGGU" # EBM, Dark-Electro & Fututepop
A7 = "spotify:playlist:5awU7dImY2OenjRFfN8WKD" # Happy Hardcore
A8 = "spotify:playlist:0DIpxrBwqAhJGOe41kYrVz" # Synthwave / Retrowave

B1 = "youtube-dl:https://www.mixcloud.com/matthiasdamasty/denbodenglatttanzen/" # faheus - #denbodenglatttanzen
B2 = "youtube-dl:https://www.mixcloud.com/matthiasdamasty/eurotrash-is-not-a-crime-live-at-gpn19/" # faheus - eurotrash is not a crime - live at #gpn19
B3 = "youtube-dl:https://www.mixcloud.com/matthiasdamasty/betreutes-chillen-live-from-new-years-eve-at-36c3-teardown/" # faheus - Betreutes Chillen - Live from New Years Eve at 36c3 Teardown
B4 = "youtube-dl:https://www.mixcloud.com/matthiasdamasty/waiting-for-breakfast-in-brown-live-from-mikrogravitation2020/" # faheus - Waiting for breakfast in brown - live from Mikrogravitation2020

B5 = "youtube-dl:https://www.mixcloud.com/couchsofa/couchsofa-schall-und-raum-live-at-mikrogravitation2020/" # Couchsofa - Schall Und Raum - live at Mikrogravitation2020
B6 = "youtube-dl:https://www.mixcloud.com/couchsofa/couchsofa-h264-aber-r%C3%BCckw%C3%A4rts-live-at-mikrogravitation2019/" # Couchsofa - H264 Aber Rückwärts - live at Mikrogravitation2019
B7 = "youtube-dl:https://www.mixcloud.com/couchsofa/couchsofa-from-bavaria-with-love-live-at-cccamp2019/" # Couchsofa - From Bavaria With Love - live at CCCamp2019
B8 = "youtube-dl:https://www.mixcloud.com/couchsofa/couchsofa-staubwiesenwedler-live-at-cccamp2019/" # Couchsofa - Staubwiesenwedler - live at CCCamp2019

# C/D: Chillout
C1 = "spotify:playlist:6Ph4rUXJKhOdrrKxSgK2ig" # Lounge Electro / Downbeat House
C2 = "spotify:playlist:37i9dQZF1DWTvNyxOwkztu" # Chillout Lounge
C3 = "spotify:playlist:37i9dQZF1DX82pCGH5USnM" # Lounge - Soft House
C4 = "spotify:playlist:37i9dQZF1DX6KItbiYYmAv" # Kaffeehausmusik
C5 = "spotify:playlist:77vsvVJ7iWB1ySfDGh1SUP" # Acustic Covers
C6 = "spotify:playlist:7BcfqemslcdlXSRbgTqkPf" # Chillout Piano
C7 = "spotify:artist:2lVC2nWo4KJE4p6EySdfkL"   # Toco - Samba
C8 = "spotify:album:3pjbc9osODpEtK1KiD2Mar"    # Samba Chill Out

D1 = "spotify:playlist:1u0bu4ezkj4QHDkfjXwKsW" # Kinderlieder zum Mitsingen
D2 = "spotify:playlist:37i9dQZF1DXe2dJQTHQvBA" # Rolf Zukowski Best Of

# E/F: Country & Folk
E1 = "spotify:playlist:37i9dQZF1DWXi7h4mmmkzD" # Country Nights
E2 = "spotify:playlist:37i9dQZF1DX8WMG8VPSOJC" # Country kind of Love
E3 = "spotify:playlist:37i9dQZF1DWYiR2Uqcon0X" # Country Coffehouse
E4 = "spotify:playlist:3GZOrKmxHmGJAGCqKMd8DW" # Country Gals
E5 = "spotify:playlist:37i9dQZF1DXdgnLr18vPvu" # Tailgate Party
E6 = "spotify:playlist:37i9dQZF1DX8S0uQvJ4gaa" # New Boots
E7 = "spotify:playlist:37i9dQZF1DX3Ee0ngF5ZVQ" # Texas Music
E8 = "spotify:album:7jZMd9n6ToKKAFzMiyC7N8"    # Country Truckin'

F1 = "spotify:playlist:4IfL5hySiXJXJApGRmOrfA" # Irisch / Gälisch / Keltisch
F2 = "spotify:playlist:3uQywS57rCK3AJTsaNLR0T" # Irish Folk Songs
F3 = "spotify:playlist:37i9dQZF1DX2ULa1Ss8vbo" # Irish Folk Ballads
F4 = "spotify:playlist:4r4J32OiWvUjJeC7e8Ewkn" # Irish Pub Songs
F5 = "spotify:playlist:3XS5jNac9kVosqa8ipk9J5" # Irish Pub Jukebox
F6 = "spotify:playlist:3ecRvUrnMsu6eW4xIA5BJJ" # Scottish Folk Songs
F7 = "spotify:playlist:4ATFk88HxkywVOY6BSaVhg" # Scottish Accordion Dance Music
F8 = "spotify:artist:3CufywuKIBC8WhWNvzTQr1"   # BBC Scottish Sympgony Orchestra

# G/H: Künstler
G1 = "spotify:artist:6kACVPfCOnqzgfEF5ryl0x" # Johnny Cash
G2 = "spotify:artist:4rp8rIXbwp93MnStnqDGQD" # Andreas Gabalier
G3 = "spotify:artist:5ISjkNS17JpCwiFtW80lpV" # Seeed
G4 = "spotify:artist:0ddfjKqJfbSiddqOvpZRWu" # Runrig
G5 = "spotify:artist:175a900UJkfGsIGcvUDaEx" # Pur
G6 = "spotify:artist:7e52Ytzjj1q71DUj2cSlch" # Sarah Connor
G7 = "spotify:artist:3gMaNLQm7D9MornNILzdSl" # Lionel Richie
G8 = "spotify:artist:3xDVmZmDpaF1uuez2N7mKl" # Tim Bendzko

H1 = "spotify:artist:5slpk6nu2IwwKx0EHe3GcL" # Lena
H2 = "spotify:artist:7IpWQKu80qQvyer3LO6SW3" # Max Herre
H3 = "spotify:artist:7uhvDINTTiD0XBrP9fquN1" # The Hooters
H4 = "spotify:artist:6XyY86QOPPrYVGvF9ch6wz" # Linkin Park
H5 = "spotify:artist:1hJuGCUpefX24GFmss9bjH" # Amy Macdonald
H6 = "spotify:artist:13YmWQJFwgZrd4bf5IjMY4" # Brad Paisley
H7 = "spotify:artist:388Jc5WX2TxTOgGwXidDM7" # Schandmaul
H8 = "spotify:playlist:37i9dQZF1DZ06evO0RQSX6" # Groove Coverage

# J/K: Künstler & Jahrzehnte
J1 = "spotify:artist:3GBPw9NK25X1Wt2OUvOwY3" # Jack Johnson
J2 = "spotify:artist:2Kx7MNY7cI1ENniW7vT30N" # Norah Jones
J3 = "spotify:artist:4lxfqrEsLX6N1N4OCSkILp" # Phil Collins
J4 = "spotify:artist:4KWTAlx2RvbpseOGMEmROg" # R.E.M.
J5 = "spotify:artist:27T030eWyCQRmDyuvr1kxY" # Scorpions
J6 = "spotify:artist:4gIdjgLlvgEOz7MexDZzpM" # Status Quo
J7 = "spotify:artist:0Ty63ceoRnnJKVEYP0VQpk" # Sting
J8 = "spotify:artist:0WwSkZ7LtFUFjGjMZBMt6T" # Dire Straits

K1 = "spotify:playlist:0CZdFXdaI14hzMPdhLwCBT" # All Out 40s
K2 = "spotify:playlist:37i9dQZF1DWSV3Tk4GO2fq" # All Out 50s
K3 = "spotify:playlist:37i9dQZF1DXaKIA8E7WcJj" # All Out 60s
K4 = "spotify:playlist:37i9dQZF1DWTJ7xPn4vNaz" # All Out 70s
K5 = "spotify:playlist:37i9dQZF1DX4UtSsGT1Sbe" # All Out 80s
K6 = "spotify:playlist:37i9dQZF1DXbTxeAdrVG2l" # All Out 90s
K7 = "spotify:playlist:37i9dQZF1DX4o1oenSJRJd" # All Out 00s
K8 = "spotify:playlist:37i9dQZF1DX5Ejj0EkURtP" # All Out 10s

# L/M: Rock & Punk Rock
L1 = "spotify:playlist:2YdBr4tvSa8xX2ea4UoWUz" # Creedence Clearwater Revival
L2 = "spotify:album:6kg3qgXaFmlXi4ik74uW7k" # Amorphis
L3 = "spotify:album:5zylhCTCHQstRpSU47BEiw" # Madrugada
L4 = "spotify:artist:61YE3whKiuRr83j1yOm5M7" # Augustana
L5 = "spotify:artist:7oPftvlwr6VrsViSDV7fJY" # Green Day
L6 = "spotify:artist:08yf5A2nS4XEeNvabDXqyg" # The Offspring
L7 = "spotify:artist:2p4FqHnazRucYQHyDCdBrJ" # Simple Plan
L8 = "spotify:artist:3Ayl7mCk0nScecqOzvNp6s" # Jimmy Eat World

M1 = "spotify:playlist:37i9dQZF1DXaQ34lqGBfrU" # Pink Floyd
M2 = "spotify:artist:22WZ7M8sxp5THdruNY3gXt" # The Doors
M3 = "spotify:artist:3vAaWhdBR38Q02ohXqaNHT" # The All-American Reject
M4 = "spotify:artist:30sqtiTKIb1oDve0SdYayT" # Anti Flag
M5 = "spotify:artist:6Wr3hh341P84m3EI8qdn9O" # Rise Against
M6 = "spotify:artist:7FBcuc1gsnv6Y1nwFtNRCb" # My Chemical Romance
M7 = "spotify:artist:6mdiAmATAx73kdxrNrnlao" # Iron Maiden
M8 = "spotify:artist:2ye2Wgw4gimLv2eAKyk1NB" # Metallica

# N/O: Swing, Jazz, Blues
N1 = "spotify:playlist:37i9dQZF1DWYotlhbgVGaH" # Swing Revival
N2 = "spotify:playlist:16aOw456cLyMMRg1WFsYDy" # Charsleton - Swing - Jazz
N3 = "spotify:playlist:37i9dQZF1DXdDe8IDhRIo5" # Gypsy Swing
N4 = "spotify:playlist:4pQrymxnlsus5rHhkX84fc" # Swingin' Saxophones

N5 = "spotify:playlist:5M7xLCQTYJL0lbKIrUn3a4" # Electro Swing 100
N6 = "spotify:artist:65EXuYHVoehCKqp0kOS6px"   # Parov Stelar
N7 = "spotify:playlist:1Wx9I2fNdPMch92AwdenLB" # Electro Jazz & Swing
N8 = "spotify:playlist:3hhSBDksTzJjBEnIaJj1gq" # Dark Electro Swing

O1 = "spotify:playlist:37i9dQZF1DWU6MDxlH7Sr1" # Happy Jazz!
O2 = "spotify:playlist:37i9dQZF1DX0SM0LYsmbMT" # Jazz Vibes
O3 = "spotify:playlist:37i9dQZF1DX55dNU0PWnO5" # Jazztronica
O4 = "spotify:playlist:37i9dQZF1DX5OepaGriAIm" # Women of Jazz

O5 = "spotify:playlist:37i9dQZF1DXd9rSDyQguIk" # Blues Classics
O6 = "spotify:playlist:37i9dQZF1DX9stbPFTxeaB" # Funk Heavy Blues
O7 = "spotify:playlist:37i9dQZF1DXcFk5r8uS3l2" # Blues Roots
O8 = "spotify:playlist:37i9dQZF1DXaOWYud3Cg4V" # Early Rhythm & Blues

# P/Q: Radio & Nachrichten
P1 = "radio:https://hr-hrinfo-live.cast.addradio.de/hr/hrinfo/live/mp3/128/stream.mp3"
P2 = "radio:https://swr-swr3-live.cast.addradio.de/swr/swr3/live/aac/96/stream.aac"
P3 = "radio:https://swr-swr1-rp.sslcast.addradio.de/swr/swr1/rp/aac/96/stream.aac"
P4 = "radio:https://hr-youfm-live.cast.addradio.de/hr/youfm/live/mp3/128/stream.mp3"
P5 = "radio:https://stream.rockland.de/rockland.mp3"

Q1 = "podcast:https://www.tagesschau.de/export/podcast/tagesthemen_https"
Q2 = "podcast:https://www.tagesschau.de/export/podcast/tagesschau_https"
Q3 = "podcast:https://theamphour.com/feed/podcast/"
Q4 = "podcast:https://minkorrekt.de/feed/m4a/"
Q5 = "podcast:https://www.hoaxilla.com/podcast/hoaxilla.xml"
Q6 = "podcast:http://web.ard.de/radiotatort/rss/podcast.xml"
Q7 = "podcast:https://www.ard.de/static/radio/radiofeature/rss/podcast.xml"
Q8 = "podcast:https://podcast.hr-online.de/hr-info_reportage/podcast.xml"
