[spotify]
client_id = ""
client_secret = ""
auth_token_storage_dir = '~/.config/jukebox/'
username = ""
device_name = "Jukebox"

[panel]
input_device_name = "panel_keys"
timeout_minutes = 10
simulate = false

[volume]
input_device_name = "volume_knob"
alsa_mixer_name = "Digital"

[leds]
host = "127.0.0.1"
port = 5555
rows = 15
leds_per_row = 11
simulate = false

[[leds.strips]] # blinky-cabinet (Cabinet)
host = "10.125.0.30"
port = 5555
index = 0
leds = 25

[[leds.strips]] # blinky-cabinet (TV)
host = "10.125.0.30"
port = 5555
index = 1
leds = 30

[animations]
A = "techno"
B = "techno"
C = "slow"
D = "slow"
E = "country"
F = "country"
G = "slow"
H = "fast"
J = "slow"
K = "slow"
L = "fast"
M = "fast"
N = "slow"
O = "slow"

P = ["solid", "#000000"]
P1 = ["solid", "#000080"]
P2 = ["solid", "#ff0000"]
P3 = ["solid", "#ffff00"]
P4 = ["solid", "#ff00ff"]
P5 = ["solid", "#ffff00"]
Q = ["solid", "#000080"]

[playback]
# A/B: House & Chillout
A1 = "spotify:playlist:37i9dQZF1DX6GJXiuZRisr" # Night Rider
A2 = "spotify:playlist:5S33MuzhWWNW57z49eBSui" # Progressive House
A3 = "spotify:playlist:3oRNodhtGLVnZl0Q32FJHB" # Deep House 2020 Hits
A4 = "spotify:playlist:37i9dQZF1DX5xiztvBdlUf" # Truely Deeply House
A5 = "spotify:album:4Ijivtrfqk2AMTF4dhrl2Q" # The Algorithm - Brute Force
A6 = "spotify:playlist:1dYAJbmobktEp59pUPeGGU" # EBM, Dark-Electro & Fututepop
A7 = "spotify:playlist:5awU7dImY2OenjRFfN8WKD" # Happy Hardcore
A8 = "spotify:playlist:0DIpxrBwqAhJGOe41kYrVz" # Synthwave / Retrowave

B1 = "spotify:playlist:6Ph4rUXJKhOdrrKxSgK2ig" # Lounge Electro / Downbeat House
B2 = "spotify:playlist:37i9dQZF1DWTvNyxOwkztu" # Chillout Lounge
B3 = "spotify:playlist:37i9dQZF1DX82pCGH5USnM" # Lounge - Soft House

B4 = "spotify:playlist:37i9dQZF1DX6KItbiYYmAv" # Kaffeehausmusik
B5 = "spotify:playlist:77vsvVJ7iWB1ySfDGh1SUP" # Acustic Covers
B6 = "spotify:playlist:7BcfqemslcdlXSRbgTqkPf" # Chillout Piano
B7 = "spotify:artist:2lVC2nWo4KJE4p6EySdfkL"   # Toco - Samba
B8 = "spotify:album:3pjbc9osODpEtK1KiD2Mar"    # Samba Chill Out

# C/D: Kinder & Seasonal
C1 = "spotify:playlist:1u0bu4ezkj4QHDkfjXwKsW" # Kinderlieder zum Mitsingen
C2 = "spotify:album:38fU1VW61DMdWabqL8psOZ" # Rolf Zukowski - Im Kindergarten
C3 = "spotify:album:6nlW6lZrQ5BO5WEFPGJGOE" # Rolf Zukowski - Der Spielmann
C4 = "spotify:album:01JrN7TzqiE7Vs1JNJ3Mkl" # Rolfs Vogehochzeit
C5 = "spotify:playlist:1YG7deML4ygSwz22AZAnO0" # Feuerwehrmann Sam
C6 = "spotify:playlist:1W6xzRMKglSHln10RHiv9i" # Paw Patrol
C7 = "spotify:album:47aRuXd0uflQQQL5xwFV9Y" # Die Eule mit der Beule
C8 = "spotify:album:3akjJKK96nen3MadP1M7Rr" # Bobo Siebenschläfer. Großer Sommerspaß.

## Karneval
#D3 = "spotify:playlist:325PoeLANQidESnexhSYZN" # Mainzer Karneval
#D4 = "spotify:playlist:2QG1qW45MV68jMsgJxexCA" # Kölner Karneval
#D5 = "spotify:playlist:6CJq5MiWjsrO4pu7DjCKj1" # Kinderkarneval
#D6 = "spotify:album:2bEfWieCBh1QhQZE8waUqn"    # Karneval-Hits 2015
#D7 = "spotify:playlist:2LLaixV9lm14M58nFbjIhX" # Karneval 70s/80s/90s
#D8 = "spotify:artist:3M7ei5iWVXuxJruRncAxUX"   # Black Fööss

## Weihnachten
D1 = "spotify:playlist:79zrdgOFGOSXtxHprgY7Xt" # Weihnachten mit Rolf Zukowski
D2 = "spotify:album:3pNMZlfhtGExgYvs1J4qF6" # Kinder Weihnachten
D3 = "spotify:album:1jHwHrbxjMXaP35UuygzQX" # Der Pianist - Klassische Weihnachten
D4 = "spotify:album:5NA85qrV1WmNNbNZJ0ORW2" # Moderne Weihnachtslieder
D5 = "spotify:playlist:37i9dQZF1DX0MuOvUqmxDz" # Country Christmas
D6 = "spotify:playlist:37i9dQZF1DWZv6UE8BMPO0" # Christmas Cocktail Jazz
D7 = "spotify:playlist:37i9dQZF1DX5kHh3pKWrss" # Weihnachten Instrumental
D8 = "spotify:album:5stoW92sMwLYf0WxOgEa16" # Rock Christmas

# E/F: Country & Folk
E1 = "spotify:playlist:37i9dQZF1DWXi7h4mmmkzD" # Country Nights
E2 = "spotify:artist:06HL4z0CvFAxyc27GXpf02" # Taylor Swift
E3 = "spotify:playlist:37i9dQZF1DWYiR2Uqcon0X" # Country Coffehouse
E4 = "spotify:playlist:3GZOrKmxHmGJAGCqKMd8DW" # Country Gals
E5 = "spotify:playlist:37i9dQZF1DXdgnLr18vPvu" # Tailgate Party
E6 = "spotify:playlist:37i9dQZF1DX8S0uQvJ4gaa" # New Boots
E7 = "spotify:playlist:37i9dQZF1DX3Ee0ngF5ZVQ" # Texas Music
E8 = "spotify:album:7jZMd9n6ToKKAFzMiyC7N8"    # Country Truckin'

F1 = "spotify:playlist:4IfL5hySiXJXJApGRmOrfA" # Irisch / Gälisch / Keltisch
F2 = "spotify:playlist:3uQywS57rCK3AJTsaNLR0T" # Irish Folk Songs
F3 = "spotify:playlist:37i9dQZF1DX2ULa1Ss8vbo" # Irish Folk Ballads
F4 = "spotify:playlist:4r4J32OiWvUjJeC7e8Ewkn" # Irish Pub Songs
F5 = "spotify:playlist:3ecRvUrnMsu6eW4xIA5BJJ" # Scottish Folk Songs
F6 = "spotify:playlist:4ATFk88HxkywVOY6BSaVhg" # Scottish Accordion Dance Music
F7 = "spotify:playlist:41Oz76GyQu7f10gfVLfnk9" # Dancehall / Reggaeton
F8 = "spotify:playlist:6RMoIh0N6NPokXLKV6AyUX" # Dancehall Classics

# G/H: Künstler
G1 = "spotify:artist:6kACVPfCOnqzgfEF5ryl0x" # Johnny Cash
G2 = "spotify:artist:4rp8rIXbwp93MnStnqDGQD" # Andreas Gabalier
G3 = "spotify:artist:5ISjkNS17JpCwiFtW80lpV" # Seeed
G4 = "spotify:artist:0ddfjKqJfbSiddqOvpZRWu" # Runrig
G5 = "spotify:artist:175a900UJkfGsIGcvUDaEx" # Pur
G6 = "spotify:artist:7e52Ytzjj1q71DUj2cSlch" # Sarah Connor
G7 = "spotify:artist:3gMaNLQm7D9MornNILzdSl" # Lionel Richie
G8 = "spotify:artist:3xDVmZmDpaF1uuez2N7mKl" # Tim Bendzko

H1 = "spotify:artist:5slpk6nu2IwwKx0EHe3GcL" # Lena
H2 = "spotify:artist:7IpWQKu80qQvyer3LO6SW3" # Max Herre
H3 = "spotify:artist:7uhvDINTTiD0XBrP9fquN1" # The Hooters
H4 = "spotify:artist:6XyY86QOPPrYVGvF9ch6wz" # Linkin Park
H5 = "spotify:artist:1hJuGCUpefX24GFmss9bjH" # Amy Macdonald
H6 = "spotify:artist:13YmWQJFwgZrd4bf5IjMY4" # Brad Paisley
H7 = "spotify:artist:5WUlDfRSoLAfcVSX1WnrxN" # Sia
H8 = "spotify:artist:6qt7HAbdjQ4a2B0sYAjySO" # Ton Steine Scherben

# J/K: Künstler & Jahrzehnte
J1 = "spotify:artist:3GBPw9NK25X1Wt2OUvOwY3" # Jack Johnson
J2 = "spotify:artist:2Kx7MNY7cI1ENniW7vT30N" # Norah Jones
J3 = "spotify:artist:4lxfqrEsLX6N1N4OCSkILp" # Phil Collins
J4 = "spotify:artist:4KWTAlx2RvbpseOGMEmROg" # R.E.M.
J5 = "spotify:artist:27T030eWyCQRmDyuvr1kxY" # Scorpions
J6 = "spotify:artist:4gIdjgLlvgEOz7MexDZzpM" # Status Quo
J7 = "spotify:artist:0Ty63ceoRnnJKVEYP0VQpk" # Sting
J8 = "spotify:artist:0WwSkZ7LtFUFjGjMZBMt6T" # Dire Straits

K1 = "spotify:playlist:0CZdFXdaI14hzMPdhLwCBT" # All Out 40s
K2 = "spotify:playlist:37i9dQZF1DWSV3Tk4GO2fq" # All Out 50s
K3 = "spotify:playlist:37i9dQZF1DXaKIA8E7WcJj" # All Out 60s
K4 = "spotify:playlist:37i9dQZF1DWTJ7xPn4vNaz" # All Out 70s
K5 = "spotify:playlist:37i9dQZF1DX4UtSsGT1Sbe" # All Out 80s
K6 = "spotify:playlist:37i9dQZF1DXbTxeAdrVG2l" # All Out 90s
K7 = "spotify:playlist:37i9dQZF1DWWnpcjfCqaW0" # 50s Country
K8 = "spotify:playlist:37i9dQZF1DX7CGYgLhqwu5" # 60s Country

# L/M: Rock & Punk Rock
L1 = "spotify:playlist:2YdBr4tvSa8xX2ea4UoWUz" # Creedence Clearwater Revival
L2 = "spotify:artist:6FBDaR13swtiWwGhX1WQsP" # blink-182
L3 = "spotify:artist:0iC8O5ABswVUFiYwM94bu3" # Madrugada
L4 = "spotify:artist:61YE3whKiuRr83j1yOm5M7" # Augustana
L5 = "spotify:artist:7oPftvlwr6VrsViSDV7fJY" # Green Day
L6 = "spotify:artist:08yf5A2nS4XEeNvabDXqyg" # Billy Talent
L7 = "spotify:artist:2p4FqHnazRucYQHyDCdBrJ" # Simple Plan
L8 = "spotify:artist:3Ayl7mCk0nScecqOzvNp6s" # Jimmy Eat World

M1 = "spotify:playlist:37i9dQZF1DXaQ34lqGBfrU" # Pink Floyd
M2 = "spotify:artist:22WZ7M8sxp5THdruNY3gXt" # The Doors
M3 = "spotify:artist:3vAaWhdBR38Q02ohXqaNHT" # The All-American Reject
M4 = "spotify:artist:6XyY86QOPPrYVGvF9ch6wz" # Linkin Park
M5 = "spotify:artist:6Wr3hh341P84m3EI8qdn9O" # Rise Against
M6 = "spotify:artist:7FBcuc1gsnv6Y1nwFtNRCb" # My Chemical Romance
M7 = "spotify:artist:6mdiAmATAx73kdxrNrnlao" # Iron Maiden
M8 = "spotify:artist:2ye2Wgw4gimLv2eAKyk1NB" # Metallica

# N/O: Swing, Jazz, Blues
N1 = "spotify:playlist:37i9dQZF1DWYotlhbgVGaH" # Swing Revival
N2 = "spotify:playlist:16aOw456cLyMMRg1WFsYDy" # Charsleton / Swing / Jazz
N3 = "spotify:playlist:37i9dQZF1DXdDe8IDhRIo5" # Gypsy Swing
N4 = "spotify:playlist:4pQrymxnlsus5rHhkX84fc" # Swingin' Saxophones

N5 = "spotify:playlist:5M7xLCQTYJL0lbKIrUn3a4" # Electro Swing 100
N6 = "spotify:artist:65EXuYHVoehCKqp0kOS6px"   # Parov Stelar
N7 = "spotify:playlist:1Wx9I2fNdPMch92AwdenLB" # Electro Jazz & Swing
N8 = "spotify:playlist:3hhSBDksTzJjBEnIaJj1gq" # Dark Electro Swing

O1 = "spotify:playlist:37i9dQZF1DWU6MDxlH7Sr1" # Happy Jazz!
O2 = "spotify:playlist:37i9dQZF1DX0SM0LYsmbMT" # Jazz Vibes
O3 = "spotify:playlist:37i9dQZF1DZ06evNZZmaDC" # Gregory Porter
O4 = "spotify:playlist:37i9dQZF1DX5OepaGriAIm" # Women of Jazz

O5 = "spotify:playlist:37i9dQZF1DXd9rSDyQguIk" # Blues Classics
O6 = "spotify:playlist:37i9dQZF1DX9stbPFTxeaB" # Funk Heavy Blues
O7 = "spotify:playlist:37i9dQZF1DXcFk5r8uS3l2" # Blues Roots
O8 = "spotify:playlist:37i9dQZF1DXaOWYud3Cg4V" # Early Rhythm & Blues

# P/Q: Radio & Nachrichten
P1 = "radio:https://hr-hrinfo-live.cast.addradio.de/hr/hrinfo/live/mp3/128/stream.mp3"
P2 = "radio:https://swr-swr3-live.cast.addradio.de/swr/swr3/live/aac/96/stream.aac"
P3 = "radio:https://swr-swr1-rp.sslcast.addradio.de/swr/swr1/rp/aac/96/stream.aac"
P4 = "radio:https://hr-youfm-live.cast.addradio.de/hr/youfm/live/mp3/128/stream.mp3"
P5 = "radio:https://stream.rockland.de/rockland.mp3"

Q1 = "podcast:https://www.tagesschau.de/export/podcast/tagesthemen_https"
Q2 = "podcast:https://www.tagesschau.de/export/podcast/tagesschau_https"
Q3 = "podcast:https://theamphour.com/feed/podcast/"
Q4 = "podcast:https://minkorrekt.de/feed/m4a/"
Q5 = "podcast:https://www.hoaxilla.com/podcast/hoaxilla.xml"
Q6 = "podcast:http://web.ard.de/radiotatort/rss/podcast.xml"
Q7 = "podcast:https://www.ard.de/static/radio/radiofeature/rss/podcast.xml"
Q8 = "podcast:https://podcast.hr-online.de/hr-info_reportage/podcast.xml"
